name: iOS CI
on:
  [pull_request]

jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
      matrix: 
        destination: ['iPhone 8']
        xcode: ['/Applications/Xcode.app/Contents/Developer']
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Bundle Install
        run: bundle install

      - name: Dependencies
        run: bundle exec pod install

      - name: Unit Tests
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: 'test'
